
package sd.tp1.clt.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AlbumAlreadyExistsException", targetNamespace = "http://srv.tp1.sd/")
public class AlbumAlreadyExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlbumAlreadyExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AlbumAlreadyExistsException_Exception(String message, AlbumAlreadyExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AlbumAlreadyExistsException_Exception(String message, AlbumAlreadyExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sd.tp1.clt.ws.AlbumAlreadyExistsException
     */
    public AlbumAlreadyExistsException getFaultInfo() {
        return faultInfo;
    }

}
