
package sd.tp1.clt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GalleryServerImplWSClassService", targetNamespace = "http://srv.tp1.sd/", wsdlLocation = "http://localhost:8080/GalleryServer?wsdl")
public class GalleryServerImplWSClassService
    extends Service
{

    private final static URL GALLERYSERVERIMPLWSCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GALLERYSERVERIMPLWSCLASSSERVICE_EXCEPTION;
    private final static QName GALLERYSERVERIMPLWSCLASSSERVICE_QNAME = new QName("http://srv.tp1.sd/", "GalleryServerImplWSClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GalleryServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GALLERYSERVERIMPLWSCLASSSERVICE_WSDL_LOCATION = url;
        GALLERYSERVERIMPLWSCLASSSERVICE_EXCEPTION = e;
    }

    public GalleryServerImplWSClassService() {
        super(__getWsdlLocation(), GALLERYSERVERIMPLWSCLASSSERVICE_QNAME);
    }

    public GalleryServerImplWSClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GALLERYSERVERIMPLWSCLASSSERVICE_QNAME, features);
    }

    public GalleryServerImplWSClassService(URL wsdlLocation) {
        super(wsdlLocation, GALLERYSERVERIMPLWSCLASSSERVICE_QNAME);
    }

    public GalleryServerImplWSClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GALLERYSERVERIMPLWSCLASSSERVICE_QNAME, features);
    }

    public GalleryServerImplWSClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GalleryServerImplWSClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GalleryServerImplWSClass
     */
    @WebEndpoint(name = "GalleryServerImplWSClassPort")
    public GalleryServerImplWSClass getGalleryServerImplWSClassPort() {
        return super.getPort(new QName("http://srv.tp1.sd/", "GalleryServerImplWSClassPort"), GalleryServerImplWSClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GalleryServerImplWSClass
     */
    @WebEndpoint(name = "GalleryServerImplWSClassPort")
    public GalleryServerImplWSClass getGalleryServerImplWSClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://srv.tp1.sd/", "GalleryServerImplWSClassPort"), GalleryServerImplWSClass.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GALLERYSERVERIMPLWSCLASSSERVICE_EXCEPTION!= null) {
            throw GALLERYSERVERIMPLWSCLASSSERVICE_EXCEPTION;
        }
        return GALLERYSERVERIMPLWSCLASSSERVICE_WSDL_LOCATION;
    }

}
