
package sd.tp1.clt.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GalleryServerImplWS", targetNamespace = "http://srv.tp1.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GalleryServerImplWS {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printCenas", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.PrintCenas")
    @ResponseWrapper(localName = "printCenasResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.PrintCenasResponse")
    @Action(input = "http://srv.tp1.sd/GalleryServerImplWS/printCenasRequest", output = "http://srv.tp1.sd/GalleryServerImplWS/printCenasResponse")
    public int printCenas();

}
